### ISSUE TITLE
Suggestion: Add a license file

### ISSUE THREAD

**Issue by uy-rrodriguez** [uclh-criu/learning-datascience#3]
Dear all, I was doing some maintenance on our repositories and just realised this open-source project doesn't have a license file yet.  Providing a separate license file instead of a note in the README is a standard approach.

A license can easily be added by creating a new file called LICENSE, with the text of the copyright notice.
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**Comment by andysouth** [comment]
Thankyou @uy-rrodriguez license file added.
